" = Plugin Manager =============================================================
call plug#begin('~/.vim/plugged')
Plug 'aklt/plantuml-syntax'
Plug 'fatih/vim-go'
Plug 'majutsushi/tagbar'
Plug 'mbbill/undotree'
Plug 'nanotech/jellybeans.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-latex/vim-latex'
Plug 'vim-scripts/Align'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'altercation/vim-colors-solarized'
"Plug 'derekelkins/agda-vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'preservim/nerdtree'
Plug 'junegunn/fzf'
call plug#end()

" ============================ Personal Configuration ==========================
filetype plugin indent on
syntax enable
syntax off
set t_Co=256
colorscheme neosimsim
set background=light
set nonumber
set autoindent
set copyindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab
set textwidth=0
set listchars=tab:>-,trail:~,extends:>,precedes:<
set list
set wrap
set spelllang=de,en
set spellsuggest=10
set scrolloff=2
set laststatus=2
set wildmenu
set wildmode=longest:full
set backspace=2
set undofile
set undodir=~/.vim/undo/,.
set backup
set backupdir=~/.vim/backup//,.
set directory=~/.vim/swap//,.
set showcmd
set mouse=a
set belloff=all
set nohls

set statusline=%F:%l:%v\ %m%r%w\|%Y\|%{&ff}\|%{&encoding}%<\|%=%3p%%\ %L

" = Key Bindings ===============================================================
nnoremap <F5> :w<CR> :silent make<CR>
inoremap <F5> <Esc>:w<CR>:silent make<CR>
vnoremap <F5> :<C-U>:w<CR>:silent make<CR>

nmap <F6> :NERDTreeToggle<CR>
nmap <S-F6> :NERDTreeFocus<CR>
nmap <F8> :TagbarToggle<CR>
nmap <F9> :SyntasticToggle<CR>
nmap <F10> :UndotreeToggle<CR>
nmap <S-F10> :UndotreeFocus<CR>

nmap <leader>h <Esc>:call ToggleHardMode()<CR>
nmap <leader>wr <Esc>:set wrap!<CR>
nmap <leader>li <Esc>:set list!<CR>
nmap <Leader>wn :match unwantedPatterns /.\+\t\|\w\zs\t\+\ze\|\W\zs\t\+\ze\|\s\+$/<CR>
nmap <Leader>fn :echo expand('%:p')<CR>
nmap [g :tabprevious<CR>
nmap ]g :tabnext<CR>
nmap [G :tabfirst<CR>
nmap ]G :tablast<CR>

noremap! <Leader>Ae Ä
noremap! <Leader>ae ä
noremap! <Leader>Oe Ö
noremap! <Leader>oe ö
noremap! <Leader>Ue Ü
noremap! <Leader>ue ü
noremap! <Leader>ss ß
noremap! <Leader>,  

source ~/.vim/uni.vim
nnoremap <Leader>u :.!uni<CR>
vnoremap <Leader>u :!uni<CR>

" LaTeX-suit
" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'

" syntastic
let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_aggregate_errors = 1
let g:syntastic_tex_chktex_args = "-n9 -n17"

" tagbar
let g:tagbar_left = 1
let g:tagbar_ctags_bin = '/usr/bin/ctags'
let g:tagbar_type_markdown = {
    \ 'ctagstype' : 'markdown',
    \ 'kinds' : [
        \ 'h:Heading_L1',
        \ 'i:Heading_L2',
        \ 'k:Heading_L3'
    \ ],
    \ 'sort'    : 0,
\ }
let g:tagbar_type_tex = {
    \ 'ctagstype' : 'latex',
    \ 'kinds'     : [
        \ 's:sections',
        \ 'g:graphics:0:0',
        \ 'l:labels',
        \ 'r:refs:1:0',
        \ 'p:pagerefs:1:0'
    \ ],
    \ 'sort'    : 0,
\ }

" Indent Guides
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1

" vim-lsp

function! s:on_lsp_buffer_enabled() abort
    setlocal omnifunc=lsp#complete
    setlocal completeopt=menu,noinsert
    setlocal signcolumn=yes
    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gr <plug>(lsp-references)
    nmap <buffer> gi <plug>(lsp-implementation)
    nmap <buffer> gt <plug>(lsp-type-definition)
    nmap <buffer> <leader>rn <plug>(lsp-rename)
    nmap <buffer> [d <Plug>(lsp-previous-diagnostic)
    nmap <buffer> ]d <Plug>(lsp-next-diagnostic)
    nmap <buffer> K <plug>(lsp-hover)
    nmap <buffer> <leader>a <plug>(lsp-code-action)
    nmap <buffer> <leader>l <plug>(lsp-code-lens)
    nmap <buffer> <leader>d <plug>(lsp-document-diagnostics)
    nmap <buffer> <leader>f <plug>(lsp-document-format)

    " refer to doc to add more commands
endfunction

augroup lsp_install
    au!
    " call s:on_lsp_buffer_enabled only for languages that has the server registered.
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
