xautolock -cornerdelay 1 -cornerredelay 5 -time 1 -locker 'slock' -corners 0-00 &
xrdb ~/.Xresources
[ -f ~/.Xresources.local ] && xrdb -merge ~/.Xresources.local
xmodmap ~/.Xmodmap
xmodmap ~/.Xmodmap.querty
sh ~/.fehbg
amixer set Master mute
amixer -c 0 set Headphone unmute
amixer -c 0 set Headphone 70

which 9 && 9 plumber -p $HOME/.plumbing
which 9 && 9 fontsrv &

signal-desktop &
wire-desktop &

exec xmonad
