export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export EDITOR="emacsclient -a ''"
export BROWSER=chromium

xautolock -cornerdelay 1 -cornerredelay 5 -time 1 -locker 'slock' -corners 0-00 &
xrdb ~/.Xresources
[ -f ~/local/Xresources ] && xrdb -merge ~/local/Xresources
xmodmap ~/.Xmodmap
xmodmap ~/.Xmodmap.querty
numlockx
[ -f ~/.fehbg ] && sh ~/.fehbg
amixer set Master mute
amixer -c 0 set Headphone unmute
amixer -c 0 set Headphone 70

# plan9port
if which 9 >/dev/null; then
  export NAMESPACE=$HOME/9p
  # export EDITOR="9 editinacme"
  export tabstop=4
  # font for sam, 9term (not acme)
  export font=/mnt/font/DejaVuSansMono/18a/font
  # a &
  9 plumber
fi

ec -n

signal-desktop &
wire-desktop &

[ -f ~/local/xinitrc ] && . ~/local/xinitrc

exec xmonad
