export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export BROWSER=chromium
export tabstop=4
# font for plan9 sam, 9term etc. (not acme)
export font=/mnt/font/DejaVuSansMono/18a/font

xautolock -cornerdelay 1 -cornerredelay 5 -time 1 -locker 'slock' -corners 0-00 &
xrdb ~/.Xresources
[ -f ~/local/Xresources ] && xrdb -merge ~/local/Xresources
xmodmap ~/.Xmodmap
xmodmap ~/.Xmodmap.querty
numlockx
[ -f ~/.fehbg ] && sh ~/.fehbg
amixer set Master mute
amixer -c 0 set Headphone unmute
amixer -c 0 set Headphone 70

which 9 && 9 plumber

signal-desktop &
wire-desktop &

[ -f ~/local/xinitrc ] && . ~/local/xinitrc

exec xmonad
