#!/bin/sh

set -e

if git st --short | grep -q '^.[^[:blank:]]'
then
cat <<EOF
You have unstaged files. This might corrupt the git-hook outcome. Either stage
them or run
git stash push -ku
git commit
git stash pop
EOF
exit 1
fi

set -v

nix build

nix build .#packagesWithGui
test -x result/bin/xmonad

nix build .#packagesWithoutGui
! test -f result/bin/xmonad

nix build .#nixosConfigurations.withGui.config.system.build.toplevel

nix build .#nixosConfigurations.withoutGui.config.system.build.toplevel
