#!/bin/sh

set -e

if git st --short | grep -q '^.[^[:blank:]]'
then
cat <<EOF
You have unstaged files. This might corrupt the git-hook outcome. Either stage
them or run
git stash push -ku
git commit
git stash pop
EOF
exit 1
fi

set -v

nix flake check
nixpkgs-fmt --check $(find . -name '*.nix' | grep -vE '(cabal|hconv)\.nix')
nix shell .#pathWithoutGui --command emacs --batch --eval "(package-activate-all)" -l dotfiles/emacs/init.el
nix shell .#pathWithGui --command emacs --batch --eval "(package-activate-all)" -l dotfiles/emacs/init.el
