#!/bin/sh

set -e

if git st --short | grep -q '^.[^[:blank:]]'
then
cat <<EOF
You have unstaged files. This might corrupt the git-hook outcome. Either stage
them or run
git stash push -ku
git commit
git stash pop
EOF
exit 1
fi

set -v

nix flake check
nix shell .#packagesWithoutGui.emacs --command emacs --batch --eval "(package-activate-all)" -l dotfiles/emacs/init.el
nix shell .#packagesWithGui.emacs --command emacs --batch --eval "(package-activate-all)" -l dotfiles/emacs/init.el
