default:
  image: nixos/nix:latest
  before_script:
    - |
      nix-env -iA \
        nixpkgs.nixUnstable \
        nixpkgs.bash \
        nixpkgs.git \
        nixpkgs.cachix

nixos:withoutGui:
  script:
    - nix --experimental-features 'nix-command flakes ca-references' build .#nixosConfigurations.withoutGui.config.system.build.toplevel

nixos:withGui:
  script:
    - nix --experimental-features 'nix-command flakes ca-references' build .#nixosConfigurations.withGui.config.system.build.toplevel

nix:packagesWithGui:
  script:
    - nix --experimental-features 'nix-command flakes ca-references' build .#packages.x86_64-linux.packagesWithGui

nix:packagesWithoutGui:
  script:
    - nix --experimental-features 'nix-command flakes ca-references' build .#packages.x86_64-linux.packagesWithoutGui
