#!/bin/sh
# remove $HOME/bin/aliases from PATH

rmFromPath() {
	case "$1" in
	'')
		;;
	*)
		PATH=`
			echo "$PATH" |
			sed '
				s,^'$1':,,g
				s,:'$1':,:,g
				s,:'$1'$,,g
			'
		`
		export PATH
		;;
	esac
}

rmFromPath "$HOME/bin/aliases"
