#!/bin/sh
# This script assumes that the alias installation directory
# in the first in PATH. It then return the second match
# of a binary name in PATH or fails of no second match is present.

rmFromPath() {
	case "$1" in
	'')
		;;
	*)
		PATH=`
			echo "$PATH" |
			sed '
				s,^'$1':,,g
				s,:'$1':,:,g
				s,:'$1'$,,g
			'
		`
		export PATH
		;;
	esac
}

rmFromPath "$HOME/bin/aliases"
