#!/bin/sh

# usage: a [font size] [acme args ...]

case $1 in
  [0-9]*)
    font_size=$1
    shift 1
    ACME_VARFONT=/mnt/font/DejaVuSans/${font_size}a/font
    ACME_FIXFONT=/mnt/font/DejaVuSansMono/${font_size}a/font
    ;;
  *)
    ACME_VARFONT=${ACME_VARFONT:-/mnt/font/DejaVuSans/17a/font}
    ACME_FIXFONT=${ACME_FIXFONT:-/mnt/font/DejaVuSansMono/17a/font}
    ;;
esac

export tabstop=${tabstob:-4}
export TERM=dumb
export NO_COLOR=1
export FORCE_COLOR=0
export SHELL=$(9 which rc)
export acmeshell="$SHELL"
export EDITOR=editinacme
export PAGER=$(9 which cat)
export GIT_PAGER=$PAGER

# Use u(1) to make sure PLAN9 is located at the end of PATH.
9 u acme -a -f $ACME_VARFONT -F $ACME_FIXFONT "$@"
