#!/bin/sh

# based on overwrite from 'The UNIX Programming Environment'

case $# in
0|1)       echo 'Usage: overwrite file cmd [args]' 1>&2; exit 2
esac

file=$1; shift

new=/tmp/overwrite.$$
trap `rm -f $new; exit 1` 1 2 15

status=0
if "$@" >$new
then
	cp $new $file
else
	echo "overwrite: $1 failed, $file unchanged" 1>&2
	status=1
fi

rm -f $new
exit $status