#!/bin/sh

set -e

ACME_VARFONT=${ACME_VARFONT:-/mnt/font/DejaVuSansMono/14a/font}
ACME_FIXFONT=${ACME_FIXFONT:-/mnt/font/FreeSans/13a/font}

export tabstop=4
export TERM=dumb
export SHELL="$(9 which rc)"
export acmeshell="$SHELL"
export PAGER=cat
export GIT_PAGER=$PAGER
export EDITOR=editinacme

exec $(9 which acme) -a -f $ACME_VARFONT -F $ACME_FIXFONT "$@"
