#!/bin/sh

set -e

ACME_VARFONT=${ACME_VARFONT:-/mnt/font/DejaVuSansMono/17a/font}
ACME_FIXFONT=${ACME_FIXFONT:-/mnt/font/DejaVuSans/17a/font}

export tabstop=4
export TERM=dumb
export NO_COLOR=1
export SHELL=$(9 which rc)
export acmeshell="$SHELL"
export EDITOR=editinacme
export PAGER=$(9 which cat)
export GIT_PAGER=$PAGER

# Use u(1) to make sure PLAN9 is located at the end of PATH.
exec 9 u acme -a -f $ACME_VARFONT -F $ACME_FIXFONT "$@"
