#!/bin/sh

module=$(echo $1 | awk -F. '{print $1}')
function=$(echo $1 | awk -F. '{print $2}')

if [ -z "$function" ]; then
   rg -nH --no-heading --color never -e 'defp? '$module $(pwd)
else
    find-ex-module $module | xargs rg -nH --no-heading --color never -e 'defp? '$function
fi
