#!/bin/sh

version=8.8.2
list=

usage() {
cat <<EOF
g [-v GHCVERSION] CMD...
g -l
g -h

Runs the given command with the given GHC version set as prefix of PATH.
Expects ghc to be installed in $APPLICATIONS/ghc-$GHCVERSION.

-v GHCVERSION	specify the GHC version (default: $version)
-l		list installed ghc versions
-h		print this help
EOF
exit 1
}

while getopts v:l name
do
	case $name in
	v) version="$OPTARG" ;;
	l) list=1 ;;
	?) usage ;;
	esac
done
shift $(($OPTIND -1))

if [ -n "$list" ]
then
	ls -1 "$APPLICATIONS" | grep -E '^ghc-'
	exit 0
fi

printf 'running `%s` within ghc-%s\n' "$*" "$version" >&2

ghcpath="$APPLICATIONS/ghc-$version"

if ! [ -d "$ghcpath" ]
then
	printf '%s not present' "$ghcpath" >&2
	exit 1
fi

PATH="$ghcpath/bin:$PATH"
export PATH

case $# in
[1-9]*)
       exec "$@"
       ;;
esac