#!/bin/sh

usage() {
cat <<EOF >&2
usage: $0 dirs... -- cmd [args..]
EOF
exit 1
}

while [ "$1" != "--" ] && [ "$1" != "" ]; do
	dirs="$dirs $1"
	shift 1
done

case $# in
  0|1) echo missing command; usage ;;
esac
shift 1

for dir in $dirs; do
(
	cd $dir
	"$@"
)
done

true
