#!/bin/sh

# Remove ansi color escape codes from commands stdin and stderr.
# Merges stdout and stderr to stdout.
# If no command is provided stdin is read
# usage: nocolor [cmd [args...]]

nocolor() {
  sed 's/\x1b\[[0-9;]*m//g'
}

case $# in
  0) nocolor ;;
  *)  exec "$@" 2>&1 | nocolor ;;
esac
